spring:
  application:
    name: pedidosservice

info:
  component: pedidosservice


server:
  port: 0


eureka:
  instance:
    instanceId: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



cloud:
  services:
    registrationMethod: route

